name: Deploy Terraform to GCS
on:
  push:
    branches:
      - dev-gcs
env:
  TF_CLOUD_ORGANIZATION: "rtrtr"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  CONFIG_DIRECTORY: "./"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure GCS credentials
        uses: google-actions/configure-google-credentials@v4
        with:
          google-access-key-id: ${{ secrets.GOOGLE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform
        run: |
          cd terraform
          terraform init
          export TF_LOG= DEBUG
          terraform plan 
          terraform apply --auto-approve
          cd ../